/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddMediaDialog: typeof import('./src/components/AddMediaDialog.vue')['default']
    CreateTopicDialog: typeof import('./src/components/CreateTopicDialog.vue')['default']
    FloatingActionButton: typeof import('./src/components/FloatingActionButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NewsCard: typeof import('./src/components/NewsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    TopicCard: typeof import('./src/components/TopicCard.vue')['default']
  }
}
